spring:
  datasource:
    url: jdbc:h2:~/jpashop;AUTO_SERVER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        default_batch_fetch_size: 500
  h2:
    console:
      enabled: true
logging:
  level:
    org.hibernate.SQL: debug